export const PLAYER_COLUMNS = [
    { key: 'playerUniqueId', label: 'Id', editable: false, className: 'w-14' },
    { key: 'name', label: 'Name', editable: true, type: 'text', className: 'min-w-36' },
    { key: 'gender', label: 'Gender', editable: true, type: 'text', className: 'w-20' },
    { key: 'group', label: 'Group', editable: true, type: 'text', className: 'w-20' },
    { key: 'rating', label: 'Rating', editable: true, type: 'text', className: 'w-20' },
    { key: 'title', label: 'Title', editable: true, type: 'text', className: 'w-16' },
    { key: 'federation', label: 'Federation', editable: true, type: 'text', className: 'w-24' },
    { key: 'fideId', label: 'FIDE Id', editable: true, type: 'text', className: 'w-24' },
    { key: 'club', label: 'Club', editable: true, type: 'text', className: 'min-w-32' },
    // { key: 'teamUniqueId', label: 'Team Id', editable: true, type: 'text', className: 'w-20' },
    { key: 'type', label: 'Type', editable: true, type: 'text', className: 'w-20' },
];

export const PLAYER_EDITABLE_KEYS = PLAYER_COLUMNS.filter(column => column.editable).map(column => column.key);
export const PLAYER_IMPORTABLE_KEYS = ['playerUniqueId', ...PLAYER_EDITABLE_KEYS];
export const PLAYER_NUMERIC_IMPORT_FIELDS = new Set(['playerUniqueId', 'rating', 'teamUniqueId', 'fideId']);
export const PLAYER_TEMPLATE_FIELDS_TEXT = PLAYER_EDITABLE_KEYS.join(', ');

export const PLAYER_FILTER_FIELDS = [
    { key: 'group', label: 'Group' },
    { key: 'federation', label: 'Fed' },
    { key: 'gender', label: 'Gender' },
    { key: 'club', label: 'Club' },
];

export const PLAYER_TARGET_OPTIONS = [
    { value: '', label: 'Ignore' },
    ...PLAYER_IMPORTABLE_KEYS.map(key => ({
        value: key,
        label: PLAYER_COLUMNS.find(column => column.key === key)?.label ?? key,
    })),
];

export const PLAYER_NATIONAL_RATING_SENTINEL = '__natrating';

export const PLAYER_VI_HEADER_FIELD_MAP = new Map([
    ['số', null],
    ['tên', 'name'],
    ['cấp', 'title'],
    ['số id', 'playerUniqueId'],
    ['rat qg', PLAYER_NATIONAL_RATING_SENTINEL],
    ['rat qt', 'rating'],
    ['ns', null],
    ['lđ', 'federation'],
    ['phái', 'gender'],
    ['loại', 'type'],
    ['nhóm', 'group'],
    ['csố', 'teamUniqueId'],
    ['clb', 'club'],
    ['số fide', 'fideId'],
    ['nguồn', null],
    ['điểm', null],
    ['hs1', null],
    ['hs2', null],
    ['hs3', null],
    ['hs4', null],
    ['hs5', null],
    ['hạng', null],
    ['họ', null],
    ['học vị', null],
]);

export const PLAYER_EN_HEADER_FIELD_MAP = new Map([
    ['no', null],
    ['number', null],
    ['birth', null],
    ['born', null],
    ['id', 'playerUniqueId'],
    ['playeruniqueid', 'playerUniqueId'],
    ['player unique id', 'playerUniqueId'],
    ['name', 'name'],
    ['gender', 'gender'],
    ['sex', 'gender'],
    ['group', 'group'],
    ['gr', 'group'],
    ['rating', 'rating'],
    ['title', 'title'],
    ['fed', 'federation'],
    ['federation', 'federation'],
    ['fideid', 'fideId'],
    ['fide id', 'fideId'],
    ['fide-no', 'fideId'],
    ['fide no', 'fideId'],
    ['fide-no.', 'fideId'],
    ['club', 'club'],
    ['teamuniqueid', 'teamUniqueId'],
    ['team id', 'teamUniqueId'],
    ['type', 'type'],
]);

export const SCORE_TARGET_OPTIONS = [
    { value: '', label: 'Ignore' },
    { value: 'round', label: 'Round' },
    { value: 'board', label: 'Board' },
    { value: 'whiteId', label: 'White ID' },
    { value: 'blackId', label: 'Black ID' },
    { value: 'whiteScore', label: 'White score' },
    { value: 'blackScore', label: 'Black score' },
    { value: 'result', label: 'Result' },
    { value: 'absentId', label: 'Absent/skip ID' },
];

export const SCORE_HEADER_FIELD_MAP = new Map([
    ['round', 'round'],
    ['rd', 'round'],
    ['r', 'round'],
    ['vong', 'round'],
    ['van', 'round'],
    ['vòng', 'round'],
    ['ván', 'round'],
    ['bd', 'board'],
    ['board', 'board'],
    ['ban', 'board'],
    ['bàn', 'board'],
    ['white id', 'whiteId'],
    ['whiteid', 'whiteId'],
    ['white', 'whiteId'],
    ['w id', 'whiteId'],
    ['id white', 'whiteId'],
    ['id-t', null],
    ['so t', 'whiteId'],
    ['sot', 'whiteId'],
    ['sốt', 'whiteId'],
    ['black id', 'blackId'],
    ['blackid', 'blackId'],
    ['black', 'blackId'],
    ['b id', 'blackId'],
    ['id black', 'blackId'],
    ['so d', 'blackId'],
    ['sod', 'blackId'],
    ['id-đ', null],
    ['sốđ', 'blackId'],
    ['white score', 'whiteScore'],
    ['white points', 'whiteScore'],
    ['w score', 'whiteScore'],
    ['w pts', 'whiteScore'],
    ['score white', 'whiteScore'],
    ['diem trang', 'whiteScore'],
    ['điểm trắng', 'whiteScore'],
    ['kq t', 'whiteScore'],
    ['kq rtgt', null],
    ['kq rtg t', null],
    ['black score', 'blackScore'],
    ['black points', 'blackScore'],
    ['b score', 'blackScore'],
    ['b pts', 'blackScore'],
    ['score black', 'blackScore'],
    ['diem den', 'blackScore'],
    ['kq d', 'blackScore'],
    ['kq rtg d', null],
    ['điểm đen', 'blackScore'],
    ['kq đ', 'blackScore'],
    ['kq rtgđ', null],
    ['result', 'result'],
    ['results', 'result'],
    ['score', 'result'],
    ['kq', 'result'],
    ['ket qua', 'result'],
    ['kqua', 'result'],
    ['vang', 'absentId'],
    ['dso', null],
    ['kết quả', 'result'],
    ['kquả', 'result'],
    ['vắng', 'absentId'],
    ['đsố', null],
    ['id-w', null],
    ['id-b', null],
    ['now', 'whiteId'],
    ['nob', 'blackId'],
    ['no w', 'whiteId'],
    ['no b', 'blackId'],
    ['resw', 'whiteScore'],
    ['resb', 'blackScore'],
    ['res w', 'whiteScore'],
    ['res b', 'blackScore'],
    ['forfeit', 'absentId'],
    ['res', 'result'],
    ['mno', null],
    ['res rtgw', null],
    ['res rtgb', null],
    ['res rtg s', null],
    ['res rtg b', null],
    ['resrtgw', null],
    ['resrtgs', null],
    ['resrtgb', null],
]);
